prometheus:
  build: "prom/"
  ports:
    - "9090:9090"
  name: prometheus
  links:
    - "exporter:export"
    - "cadvisor:cadvisor"

exporter:
  image: "prom/container-exporter"
  volumes:
    - /sys/fs/cgroup:/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9104:9104"
  expose:
    - "9104"
  name: exporter

sqlite3:
  image: "prom/promdash"
  command:
    - "./bin/rake db:migrate"
  volumes:
    - "/tmp/prom:/tmp/prom"
  environment:
    - "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"

promdash:
  image: "prom/promdash"
  ports:
    - "3000:3000"
  expose:
    - "3000"
  volumes:
    - /tmp/prom:/tmp/prom
  environment:
    - "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"
  name: "promdash"

cadvisor:
  image: "google/cadvisor"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  ports:
    - "8080:8080"
  expose:
    - "8080"
  name: "cadvisor"
